apiVersion: v1
kind: Service
metadata:
  name: podinfo-frontend2
  namespace: podinfo-frontend2
spec:
  selector:
    app: podinfo
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
