apiVersion: v1
kind: Service
metadata:
  name: podinfo-backend2
  namespace: podinfo-backend2
spec:
  selector:
    app: podinfo
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
